server:
  port: 9002 #服务端口
spring:
  application:
    name: FEIGN-CONSUMER   #feign consumer在Eureka的服务名称，随便取
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/   #注册到Eureka的地址，与服务端的配置保持一致